[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = False

[mypy-tests.*]
check_untyped_defs = False
disallow_untyped_defs = False

[mypy-requests]
ignore_missing_imports = True